config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  #ログイン機能の　gem deviseを利用する際にはアカウントを作成するためのUserモデルを新しく作成します。
  devise_for :installs
  root to: 'posts#index' #/にアクセスしたらこれでindex画面に飛ばす
  namespace :posts do
    resources :searches, only: :index
  end
  resources :posts do
    resources :comments, only: [:create]
    # 7つの基本アクション以外(search)は、collectionかmember
    # collectionはルーティングに:idがつかない、memberは:idがつく
    # 今回の検索機能の場合、詳細ページのような:idを指定して特定のページにいく必要がないため、collectionを使用してルーティングを設定しましょう。
    end
    # resourcesは、7つのアクションをまとめてルーティングの設定ができるので7つのアクション全てを記述した今、only以下は不要
  # only: [:index, :new, :create, :show, :edit, :update, :destroy]
  # コメントには必ずコメント先となる投稿が存在しています。
  # ネストによって、/tweets/:tweet_id/comments(.:format)となっています。
  # リンクを飛ばすときは、この:tweet_idのところにコメントと結びつくツイートのidを記述します。
  # すると、paramsのなかにtweet_idというキーが追加され、コントローラーで扱うことができます。
  # rails routesにより
  # ルーティングをネストさせる一番の理由はアソシエーション先のレコードのidを
  # paamsに追加してコントローラーに送るためです。
  # 今回の実装だと、コメントと結びつく投稿（ぽすと）のidをparamsに追加しています。



  resources :users, only: :show
  # マイページを表示する際にはusersコントローラーのshowアクションを動かします。
  # rails routesで出る
  # user GET    /users/:id(.:format)     users#show
  # :idの部分には表示するユーザーページのユーザーのidが入ります。
  # コントローラー内でparams[:id]と記述することにすれば/users/:idの:id部分の情報を使用することができます。
end
  # 　マイページの詳細を見るやーつrails g controller users 忘れずに


# resources :posts, except: :index
# exceptを使用するとindexのみ除外？という意味

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
  validates :name, :age, :onset, :title, :allergy, presence: true

  belongs_to :user
  has_many :comments

#   def self.search(search)
#     return Post.all unless search
#     Post.where('text LIKE(?)', "%#{search}%")
#   end
# end
# どっちでも大丈夫
  def self.search(search)
    if search
      Post.where('name LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

# モデルにテーブルから検索するためのメソッドsearchを定義していきます。
# MVCの観点で検索するなどのビジネスロジック（プログラムの処理の流れ）は、メソッドとしてモデルにまとめて定義するようにします。
# 理由は、そのメソッドを別の場所でも使うことができ、チーム開発などにおいても便利だからです。

# モデル.where(条件)のように引数部分に条件を指定することで、テーブル内の条件に一致したレコードのインスタンスを配列の形で取得できます。

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

# deviseでは初期状態でサインアップ時にメールアドレスとパスワードのみを受け取るようにストロングパラメーターが設定してあるので、
# 追加したキー（nickname）のパラメーターは許可されていません。

# 追加のパラメーターを許可したい場合は、application_controller.rb
# においてbefore_actionにconfigure_permitted_parametersメソッドを設定します。

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    Comment.create(comment_params)
    # redirect_to "/"  # コメントと結びつく投稿の詳細画面に遷移する
    redirect_back(fallback_location: root_path)
    # 一つ前に戻る技発見
    # redirect_to "/posts/#{comment.post.id}"#これ使用したいがエラー出る
    # post_comments POST   /posts/:post_id/comments(.:format)                                                       comments#create


    # tweetsコントローラのshowアクションを実行するにはツイートのidが必要です。
    # そのため、ストロングパラメーターを用いた上で変数commentに代入します。
    # リダイレクト先の指定には、アソシエーションを利用してcommentと結びつくツイートのidを記述しています。
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end
# user_idカラムには、ログインしているユーザーのidとなるcurrent_user.idを保存し、
# post_idカラムは、paramsで渡されるようにするので、params[:post_id]として保存しています。

app/controllers/posts/searches_controller.rb
class Posts::SearchesController < ApplicationController
  def index
    @posts = Post.search(params[:keyword])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit]
  before_action :move_to_index, except: [:index, :show, :search]
  # indexアクションにアクセスした時、indexアクションへのリダイレクトを繰り返し無限ループが起こるので、
  # except:を付け加えます。
  # また、詳細ページへはログインする必要はないものとするために
  # except: [:index, :show]としています。
  # 未ログイン状態にトップページへリダイレクトされてしまうことを回避するため、before_actionのexceptオプションに:searchを追加しています。

  # 42~44行




  # 一覧表示ページを表示するリクエストに対応して動く
  def index
    # @post = Post.find(1)  # 1番目のレコードを@postに代入しviewへ写す
    # @posts = Post.all
    @posts = Post.includes(:user).order("created_at DESC").page(params[:page]).per(3)
    #全てのレコードを@postsに代入 複数データの為、post→postsへ
    # @posts = Post.includes(:user) #includesを使用することによりn1問題の解消に。
#     これをつけるだけでpostsテーブルのレコードを取得する段階で関連するusersテーブルのレコードも一度に取得することができます。
#     処理が速くなります。
# テーブルのレコード数が多くなるほど処理速度の差が大きくなるので、アソシエーションを組んだ際は必ずincludesメソッドを利用して対策しましょう。
  end

# 新規投稿ページを表示するリクエストに対応して動く
  def new
    @post = Post.new
  end

# データの投稿を行うリクエストに対応して動く
  def create
    # binding.pry
    # Post.create()の()には、実際にPostテーブルに登録したいデータを記載します。
    # Post.create(content: params[:content]) #左側がカラム名（contentカラム）
    # 右側がparamsとして送られて来たデータを表現　ただこれは正しい表記ではないので下に記載
    Post.create(post_params) #post_paramsってなんやねん　下へ
    # @posts = Post.includes(:user).order("created_at DESC").page(params[:page]).per(5)

    # @posts = Post.page(params[:page]).per(5)
    # orderメソッドの引数として("created_at DESC")を足すだけで、レコードは逆順に並び替えられます。
    # kaminariによってリクエストの際paramsの中にpageというキーが追加されています。
    # その値がビューで指定したページ番号となるため、pageの引数はparams[:page]となります。


    # createアクションはフォームで送られてきた情報を元に、レコードを保存します。
    # ストロングパラメーターも忘れずに設定しましょう。
    # @posts = Post.all
    redirect_to root_path
    # リダイレクトさせるパスは、Prefixと_pathを用いて、ルートパスを指定しています。
  end

  # 個別詳細ページを表示するリクエストに対応して動く
  def show
  @comment = Comment.new
  @comments = @post.comments.includes(:user)
  # posts/show.html.erbでform_withを使用して、comments#createにアクション先を飛ばしたいので、
  # @comment = Comment.newとインスタンス生成をしないといけません。
  # ビューでは誰のコメントかを明らかにするためアソシを使ってユーザーのレコードを取得
  # その時に「N+1問題」が発生してしまうので、includesメソッド使用
# では、コントローラーであるpostsについて投稿されたコメントの全レコードを取得することができたので、これらをビューで表示しましょう。
  end

  def search
  @posts = Post.search(params[:keyword])
  end

  # 投稿編集ページを表示するリクエストに対応して動く
   def edit
    # @post = Post.find(params[:id])
    # params[:id]は元々レコードのIDが入っていたので、
    # IDに該当するレコードの全ての情報をテーブルから取得し編集をする
    # @postには編集するブログの情報が入るようになっています。
   end

  #  データの編集を行うリクエストに対応して動く
   def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  # データの削除を行うリクエストに対応して動く
  def destroy
    post = Post.find(params[:id])
    post.destroy
    # redirect_to root_path
  end

  def model_name
  end



  private
  def post_params
    params.require(:post).permit(:name, :nickname, :title, :onset, :sex, :asthma, :age, :allergy, :kusuri, :image).merge(user_id: current_user.id)
    #  うえの(post_params)の答え。カレントはログイン中のidを取得できる。mergeは前後の情報を合体
    # 投稿を保存する際、name、image、textというビューから送られてくる情報に加えて、user_idカラムにログイン中のユーザーのidを保存しなければいけません。
    # そのため、2つのハッシュを統合する時に使うmergeメソッドを利用して、user_idを統合しましょう。
    # user_idは、ログイン中のユーザーidが必要なため、current_user.idと記述することで取得が可能
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in? #ユーザーがログインしていない時にはindexアクションを実行する
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    # binding.pry
    @user = User.find(params[:id])
    # @posts = @user.posts
    @posts = @user.posts.page(params[:page]).per(3).order("created_at DESC")
  end
end


# マイページに必要な情報は
# ユーザー情報　@user = User.find(params[:id])
# ログイン中のユーザーの投稿　    @posts = @user.posts
# の2つ

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts/searches_helper.rb
module Posts::SearchesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="style.css">
    <title>市販薬選択アプリ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# application.html.erbのstylesheet_link_tagの部分にapplicationと書いてあるので、このHTMLからはapp/assets/stylesheets/application.cssというCSSファイルを読み込むことを示しています。 %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <%# <div class="titles"> %>
    <nav>
      <ul class="header-links">
        <%# <li class="header-link"><a href="https://www.mhlw.go.jp/file/06-Seisakujouhou-11120000-Iyakushokuhinkyoku/0000180831.pdf">世界一分かりやすいお薬の知識</a></li> %>
        <li class="header-link"><a href="https://www.kusurinomadoguchi.com/near">処方箋受付が可能な薬局を探す</a></li>
        <li class="header-link"><a href="https://pharmacy-search.jp/">近隣のドラッグストアを探す</a></li>
        <%# <li class="header-link"><a href="https://www.nttdocomo.co.jp/service/okusuri_link/">お薬手帳リンクサービス</a></li> %>
      </ul>
    </nav>
    <div class="title">
      <h1 style="font-size: 130px; margin: 50px;">okusuri_app</h1>
    </div>
    <div class="header">
      <div class="header__title">
        </div>
      <div class="header__right">
        <% if user_signed_in? %>
        ログイン名：<%= link_to current_user.nickname, user_path(current_user), class: "header__right--btn" %>の投稿一覧
        <%= link_to "新規投稿", new_post_path, class: "header__right--btn" %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__right--btn" %>
        <% else %>
        <%= link_to "ログイン", new_user_session_path, class: "header__right--btn" %>
        <%= link_to "新規登録", new_user_registration_path, class: "header__right--btn" %>
        <% end %>
      </div>
    </div>
  <div class="contents">
    <%= yield %>
  </div>
</html>

app/views/posts/_date.html.erb
<div class="date">
  <div class="posts1">
    <div class="post">　　
      <h2>①症状 <span class="required">必須</span></h2>　
      <%= form.text_area :name, placeholder: "熱・あせも・下痢など", class: :form__name %>
    </div>
    <div class="post">　　
      <h2>❷性別 <span class="required">必須</span></h2>　
      <%= form.text_area :sex, placeholder: "男性・女性", class: :form__name %>
    </div>
  </div>
  <div class="posts2">
    <div class="post">　　
      <h2>③年齢 <span class="required">必須</span></h2>　
      <%= form.number_field :age, placeholder: "↓↑", class: :form__age, min: 0, max: 150 %>
    </div>
    <div class="post">　　
      <h2>❹時期 <span class="required">必須</span></h2>　
      <%= form.text_area :onset, placeholder: "１週間前から", class: :form__name %>
    </div>
  </div>
  <div class="posts3">
    <div class="post">
      <h2>⑤アレルギー <span class="required">必須</span></h2>　
      <%= form.text_area :allergy, placeholder: "牛乳アレルギーなど記載", class: :form__name %>
    </div>
    <div class="post">　　
      <h2>❻喘息の有無 <span class="required">必須</span></h2>　
      <%= form.text_area :asthma, placeholder: "あり・なし", class: :form__name %>
    </div>
  </div>
  <div class="posts4">
    <div class="post">
      <h2>⑦部位の画像</h2>
      <%= form.text_area :image, placeholder: "その部位の写真", class: :form__name %>
    </div>
    <div class="post">
      <h2>❽現在服用しているお薬 <span class="required">必須</span></h2>
      <%= form.text_area :kusuri, placeholder: "例：ロキソニン・高血圧のお薬・血液をサラサラにするお薬", class: :form__name %>
    </div>
  </div>
<div class="post">
  <h2>⑨具体的な症状の説明をお願い致します <span class="required">必須</span></h2>　
  <%= form.text_area :title, placeholder: "例：熱が特にひどく、喉も痛いです。私はコロナなのでしょうか？", class: :form__title,rows: "7"%>
</div>
<%= form.submit "投稿", class: :form__btn %>

app/views/posts/_post.html.erb
<div class="content">
    <div class="contents">
      <div class="content__1">
        <div class="content__1__title">
          <h2>症状</h2>
          <%= link_to post.name, post_path(post.id), class: "content__1__title--answer" %>
        </div>
      </div>
      <div class="content__2">
        <%# <div class="sex">
          <h2>性別</h2>
          <div class="sex__answer">
            <%= post.sex %>
          <%# </div>
        </div> %>
        <div class="age">
          <h2>年齢</h2>
          <div class="age__answer">
            <%= post.age %>歳
          </div>
        </div>
        <div class="created_at">
          <h2>投稿時間</h2>
          <div class="created_at__answer">
            <%= post.created_at %>
          </div>
        </div>
      </div>
      <div class="content__3">
        <h2>投稿者</h2>
        <%= link_to post.user.nickname, user_path(post.user), class: "content__3" %>
      </div>
    </div>
</div>

<%# 部分テンプレートのファイル名は必ずアンダーバー「_」から始まります。 %>
<%# HTML構造の部分を共通化することによって、無駄なくビューファイルを作成することができます。この共通化された部分を、 部分テンプレート %>

app/views/posts/destroy.html.erb
<!DOCTYPE html>
  <div lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>サイト</title>
    <link rel="stylesheet" href="reset.css">
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
      <div class="success">
        <h3>
          削除が完了しました。
        </h3>
        <a class="btn" href="/">トップページへ戻る</a>
      </div>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="content__title">
  <%= link_to 'メインページへ戻る', '/posts/' %>
</div>
  <h3>投稿の編集画面</h3>
<%= form_with model: @post, class: :form, local: true do |form| %>
  <%#ajax通信はこのアプリにはないので、それをキャンセルするためにlocal: trueオプション %>
<%= render partial: "date", locals: { form: form } %>
    <%# form_withの中では、formという変数を利用しているので、locals: { form: form }という記述になっていることに注意しましょう。 %>
<% end %>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="style.css">
  <title>KojinnApp</title>
</head>
  <body>
    <script src="script.js"></script>
  </body>
</html>
<div class="wrapper">
  <main>
    <section class="fv-section">
      <p class="main-copy">
      <b>アプリの目的</b>
      </p>
      <p class="fv-text">♦︎投稿者の症状に合う市販薬を薬剤師が選択する</p>
      <p class="fv-text">♦︎そのお薬を選択した内容を公表することで</p>
      <p class="fv-text">♦全国の登録販売者・お客様のお薬の知識の向上を目指す</p>
      <a href="/posts/new" class="cta-btn">GO</a>
    </section>
  </main>
  <div class= "postContent">
    <h1></h1>
    <%# <%= link_to '1つ戻る', '/posts/new' %>
    <%= form_with(url: posts_searches_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "学びたい症状を入力", class: "search-input" %>
    <%= form.submit "click!", class: "search-btn" %>
    <% end %>
    <div class="postTitles">
      <% @posts.each do |post| %>
      <%= render partial: "post", locals: { post: post } %>
      <%# renderメソッドで使用できるオプションです。 partialというオプションを付けることで、
      明示的に部分テンプレート名を指定し、部分テンプレートを表示することができます。
      今回は、_post.html.erbという部分テンプレートを呼び出しています。 %>
      <%# 右側のpostはeachメソッド内の変数としてのpostでpostのインスタンスを示しています。
      左側のpostは部分テンプレート内での変数の名前を表しています。 %>
      <% end %>
      <%= paginate(@posts)%>
    </div>
  </div>
  <footer>
    <small>I want to change drugstore with this app
    </small>
  </footer>
</div>

app/views/posts/new.html.erb
<h1>本日の接客内容を記載してください</h1>
<%= link_to 'メインページに戻る', '/posts' %>
  <div class= "posts">
    <%= form_with model: @post, class: :form, local: true do |form| %>
    <%= render partial: "date", locals: { form: form } %>
    <%# form_withの中では、formという変数を利用しているので、locals: { form: form }という記述になっていることに注意しましょう。 %>
    <% end %>
  </div>

app/views/posts/search.html.erb
<div class= "postContent">
  <h1>症状検索結果</h1>
  <%= link_to '1つ戻る', '/posts/new' %>
  </div>
<div class="postTitles">
  <% @posts.each do |post| %>
  <%= render partial: "post", locals: { post: post } %>
<%# renderメソッドで使用できるオプションです。 partialというオプションを付けることで、
明示的に部分テンプレート名を指定し、部分テンプレートを表示することができます。
今回は、_post.html.erbという部分テンプレートを呼び出しています。 %>
<%# 右側のpostはeachメソッド内の変数としてのpostでpostのインスタンスを示しています。
左側のpostは部分テンプレート内での変数の名前を表しています。 %>
  <% end %>
<%# <%= paginate(@posts)%>
</div>

app/views/posts/searches/index.html.erb
<div class= "postContent">
  <h1>症状検索結果</h1>
  <%= link_to '投稿一覧に戻る', '/posts' %>
  </div>
<div class="postTitles">
  <% @posts.each do |post| %>
  <%= render partial: "posts/post", locals: { post: post } %>
<%# renderメソッドで使用できるオプションです。 partialというオプションを付けることで、
明示的に部分テンプレート名を指定し、部分テンプレートを表示することができます。
今回は、_post.html.erbという部分テンプレートを呼び出しています。 %>
<%# 右側のpostはeachメソッド内の変数としてのpostでpostのインスタンスを示しています。
左側のpostは部分テンプレート内での変数の名前を表しています。 %>
  <% end %>
<%# <%= paginate(@posts)%>
</div>

app/views/posts/show.html.erb
<div class= "back">
  <%= link_to 'メインページに戻る', '/posts' %>
</div >
<div class="postTitle">

  <h1>お困りの症状『<%= @post.name %>』</h1>
  <%# <> 私がお勧めしたお薬：<%= @post.nickname%>
</div>
<% if user_signed_in? && current_user.id == @post.user_id %>　
<%# ①ログインしてます？　　②ログインしているユーザー　と　投稿したユーザーが一致してます？ それなら編集・削除して良いですよ %>
  <div class="postManage">
    <%= link_to "編集", edit_post_path(@post.id), class: "postManage__edit"%>
    <%= link_to "削除", post_path(@post.id),method: :delete,class: "postManage__delete",data: {confirm: "消すなんて嘘だろ?"} %>
    <%# <%= link_to "1つ戻る",'Create', 'posts_path'なぜかトップに行っちゃう %>
  </div>
<% end %>
<div class="post_content">
  <div class="result">
    <div class="posts1">
      <div class="post">　　
        <h2>❶症状</h2>　
        <%= @post.name %>
      </div>
      <div class="post">　　
        <h2>❷性別</h2>　
        <%= @post.sex%>
      </div>
      <div class="post">　　
        <h2>❸年齢</h2>　
        <%= @post.age %>歳
      </div>
      </div>
    <div class="posts2">
      <div class="post">　　
        <h2>❹発症時期</h2>　
          <%= @post.onset %>
      </div>
      <div class="post">
        <h2>❺アレルギー</h2>　
        <%= @post.allergy %>
      </div>
      <div class="post">　　
        <h2>❻喘息</h2>　
        <%= @post.asthma%>
      </div>
    </div>
    <div class="posts3">
      <div class="post">
        <h2>❼画像</h2>　
        <div class="image">
        <div class="postImage" style="background-image:url(<%= @post.image %>);">
        </div>
        </div>
      </div>
      <div class="post">
        <h2>❽現在服用しているお薬</h2>　
        <%= simple_format @post.kusuri %>
      </div>
    </div>
    <div class="post">　　
      <h2>❾具体的な症状の内容</h2>　
      　　<%= simple_format @post.title %>
    </div>
  </div>
    <div class="chat">
      <h2>薬剤師に相談ができます</h2>
        <div class="container">
          <% if current_user %>
            <%= form_with(model: [@post, @comment], local: true) do |form| %>
              <%= form.text_area :text, placeholder: "コメントする", rows: "3" %>
              <%= form.submit "SEND" %>
            <% end %>
          <% else %>
            <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
          <% end %>
        </div>
      </div>
    <div class="comments">
      <h4>⬇︎薬剤師への相談内容⬇︎</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
        <div class="comment">
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        </div>
        <% end %>
      <% end %>
</div>

</div>

app/views/users/show.html.erb
<div class= "back">
  <%= link_to 'メインページへ戻る', '/posts/' %>
</div>
<div class="postTitle">
  <div class="postname">
    「<%= @user.nickname %>」投稿一覧
  </div>
    <% @posts.each do |post| %>
      <div class="content">
        <div class="content__top">
          <div class="content__top--image"></div>
        </div>
        <div class="content__bottom">
          <div class="content__bottom__top">
            <p>接客内容</p>
            <%= link_to post.name, post_path(post.id), class: "content__bottom__top--title" %>
          </div>
          <div class="content__bottomu__bottom">
            お薬は「<%= post.nickname %>」をお勧めしました！
            <div class="content__bottom__bottom--userName">
              <p>投稿者</p>
              <%= link_to post.user.nickname, user_path(post.user), class: "content__bottom__bottom--userName--btn" %>
            </div>
            <div class="content__bottom__bottom--date">
              <%= post.created_at %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <%= paginate(@posts)%>
</div>